// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(ControlVacunaContext))]
    [Migration("20201114233713_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Persona", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("Date");

                    b.Property<string>("InstitucionEducativa")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NombreAcudiente")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NombreEstudiante")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("varchar(11)");

                    b.HasKey("Identificacion");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Entity.Vacuna", b =>
                {
                    b.Property<int>("VacunaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("EdadAplicacion")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaVacuna")
                        .HasColumnType("Date");

                    b.Property<string>("IdentificacionPersona")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NombreVacuna")
                        .HasColumnType("varchar(20)");

                    b.HasKey("VacunaId");

                    b.ToTable("Vacunas");
                });
#pragma warning restore 612, 618
        }
    }
}
